### 1. Crear un Grupo Electrogeno (POST)
POST http://localhost:8080/api/v1/grupos-electrogenos
Content-Type: application/json

{
  "codigo": "G-POW-500",
  "vidaUtil": 10,
  "tipoCombustible": "GASOIL",
  "tipoArranque": "AUTOMATICO",
  "pMin": 100,
  "pMax": 500,
  "insonorizado": true,
  "capo": true
}

### 2. Cotizar Precio Real (GET)
GET http://localhost:8080/api/v1/grupos-electrogenos/1/precio

### 3. Obtener el Grupo Creado (GET)
GET http://localhost:8080/api/v1/grupos-electrogenos/1

### 4. Crear una Solicitud de Compra (Asignacion Automatica)
POST http://localhost:8080/api/v1/ventas
Content-Type: application/json

{
  "nombreSolicitante": "Ing. Juan Perez",
  "entidadId": 1,
  "tipoPago": "EFECTIVO",
  "cantidad": 2,
  "potenciaRequerida": 300,
  "tipoCombustible": "GASOIL",
  "vidaUtilSolicitada": 5
}

### 5. Ver Ingresos Totales
GET http://localhost:8080/api/v1/ventas/ingresos-totales
