### 0. Auth - Login Admin
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

> {% client.global.set("auth_token", response.body.token); %}

### 1. Crear un Grupo Electrogeno (POST) - ADMIN REQUIRED
POST http://localhost:8082/api/v1/grupos-electrogenos
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "codigo": "G-POW-500",
  "vidaUtil": 10,
  "tipoCombustible": "GASOIL",
  "tipoArranque": "AUTOMATICO",
  "pMin": 100,
  "pMax": 500,
  "insonorizado": true,
  "capo": true
}

### 2. Cotizar Precio Real (GET) - PUBLIC
GET http://localhost:8082/api/v1/grupos-electrogenos/1/precio

### 3. Obtener el Grupo Creado (GET) - PUBLIC
GET http://localhost:8082/api/v1/grupos-electrogenos/1

### 4. Crear una Solicitud de Compra (POST) - ADMIN REQUIRED
POST http://localhost:8082/api/v1/ventas
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "nombreSolicitante": "Ing. Juan Perez",
  "entidadId": 1,
  "tipoPago": "EFECTIVO",
  "cantidad": 2,
  "potenciaRequerida": 300,
  "tipoCombustible": "GASOIL",
  "vidaUtilSolicitada": 5
}

### 5. Ver Ingresos Totales - PUBLIC
GET http://localhost:8082/api/v1/ventas/ingresos-totales
