# Perfil de Test - H2 en Archivo
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# CORS Test
cors.allowed-origins=http://localhost:3000
