# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (H2 En Memoria)
# ===============================
spring.datasource.url=jdbc:h2:mem:grupos_electrogenos_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola web de H2 para que puedas ver tus tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# CONFIGURACIÓN DE JPA E HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true