# Perfil activo por defecto
spring.profiles.active=dev

# Configuración común
server.port=${PORT:8082}
spring.main.allow-bean-definition-overriding=true

# JWT Configuration
jwt.secret=${JWT_SECRET:mi_secreto_super_seguro_que_debe_ser_largo_y_complejo_para_produccion_HS256}
jwt.expiration=${JWT_EXPIRATION:3600000}