-- Baseline del esquema de producción (PostgreSQL).
-- Generado a partir del modelo JPA actual. A partir de aquí JPA solo valida
-- (ddl-auto=validate); Flyway es la única fuente de evolución del esquema.

CREATE TABLE entidades (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE grupos_electrogenos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo           VARCHAR(255) NOT NULL UNIQUE,
    capo             BOOLEAN,
    insonorizado     BOOLEAN,
    p_max            FLOAT(53) NOT NULL,
    p_min            FLOAT(53) NOT NULL,
    stock            INTEGER NOT NULL CHECK (stock >= 0),
    vida_util        INTEGER NOT NULL CHECK (vida_util >= 1),
    tipo_arranque    VARCHAR(255) NOT NULL CHECK (tipo_arranque IN ('AUTOMATICO', 'MANUAL')),
    tipo_combustible VARCHAR(255) NOT NULL CHECK (tipo_combustible IN ('NAFTA', 'GAS_NATURAL', 'GASOIL')),
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE grupos_electrogenos_moviles (
    id              BIGINT NOT NULL,
    cantidad_ruedas INTEGER NOT NULL CHECK (cantidad_ruedas >= 1),
    material_eje    VARCHAR(255) NOT NULL CHECK (material_eje IN ('ACERO', 'ALEACION')),
    PRIMARY KEY (id)
);

CREATE TABLE roles (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE solicitudes_compra (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    identificador        VARCHAR(255) NOT NULL UNIQUE,
    nombre_solicitante   VARCHAR(255) NOT NULL,
    cantidad             INTEGER NOT NULL CHECK (cantidad >= 1),
    potencia_requerida   FLOAT(53) NOT NULL,
    vida_util_solicitada INTEGER NOT NULL CHECK (vida_util_solicitada >= 1),
    tipo_combustible     VARCHAR(255) NOT NULL CHECK (tipo_combustible IN ('NAFTA', 'GAS_NATURAL', 'GASOIL')),
    tipo_pago            VARCHAR(255) NOT NULL CHECK (tipo_pago IN ('CHEQUE', 'EFECTIVO')),
    entidad_id           BIGINT NOT NULL,
    grupo_id             BIGINT NOT NULL,
    created_at           TIMESTAMP(6),
    updated_at           TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE usuarios (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE usuarios_roles (
    usuario_id BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    PRIMARY KEY (role_id, usuario_id)
);

-- Índices
CREATE INDEX idx_grupo_combustible ON grupos_electrogenos (tipo_combustible);
CREATE INDEX idx_grupo_movil_material ON grupos_electrogenos_moviles (material_eje);
CREATE INDEX idx_solicitud_identificador ON solicitudes_compra (identificador);
CREATE INDEX idx_solicitud_entidad ON solicitudes_compra (entidad_id);

-- Claves foráneas
ALTER TABLE grupos_electrogenos_moviles
    ADD CONSTRAINT fk_movil_grupo FOREIGN KEY (id) REFERENCES grupos_electrogenos;
ALTER TABLE solicitudes_compra
    ADD CONSTRAINT fk_solicitud_entidad FOREIGN KEY (entidad_id) REFERENCES entidades;
ALTER TABLE solicitudes_compra
    ADD CONSTRAINT fk_solicitud_grupo FOREIGN KEY (grupo_id) REFERENCES grupos_electrogenos;
ALTER TABLE usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_role FOREIGN KEY (role_id) REFERENCES roles;
ALTER TABLE usuarios_roles
    ADD CONSTRAINT fk_usuarios_roles_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;
